name: My Second Workflow

on:
  push:
    branches:
      - main

jobs:
  explore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Current Directory
        run: pwd

      - name: List Files
        run: ls -la

      - name: Print Message
        run: echo "Learning GitHub Actions"
